### ISSUE TITLE
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

### ISSUE THREAD

**Issue by QYw12** [BaiShuanghao/Prompt-based-Distribution-Alignment#9]
Hello author, during the training phase, I encountered this error while typing bash commands. I would like to ask how to solve it, as follows:
# params: 3,511,937
Constructing source feature bank...
Traceback (most recent call last):
  File "train.py", line 309, in <module>
    main(args)
  File "train.py", line 259, in main
    trainer = build_trainer(cfg)
  File "/home/ailab/Dassl.pytorch/dassl/engine/build.py", line 11, in build_trainer
    return TRAINER_REGISTRY.get(cfg.TRAINER.NAME)(cfg)
  File "/home/ailab/Dassl.pytorch/dassl/engine/trainer.py", line 325, in __init__
    self.build_model()
  File "/mnt/4T/QY/Prompt-based-Distribution-Alignment/trainers/da/pda.py", line 340, in build_model
    self.construct_bank()
  File "/home/ailab/anaconda3/envs/pda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/4T/QY/Prompt-based-Distribution-Alignment/trainers/da/pda.py", line 392, in construct_bank
    self.model(input, label=label, construct=True)
  File "/home/ailab/anaconda3/envs/pda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/4T/QY/Prompt-based-Distribution-Alignment/trainers/da/pda.py", line 203, in forward
    prompts, deep_ctx, vctx, deep_vctx = self.prompt_learner()
  File "/home/ailab/anaconda3/envs/pda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/4T/QY/Prompt-based-Distribution-Alignment/trainers/da/pda.py", line 143, in forward
    vctx = self.proj(self.ctx)
  File "/home/ailab/anaconda3/envs/pda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ailab/anaconda3/envs/pda/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

**Comment by BaiShuanghao** [comment]
CPU does not support half-precision (float16) data type calculations. The computation needs to be moved to the GPU.
